### ISSUE TITLE
Gives Error 500 after Authentication by Miele

### ISSUE THREAD

**Issue by jayatgithub** [HomeAssistant-Mods/home-assistant-miele#46]
After authentication through Miele Website and going back to HA (with token), HA gives Error 500 (with no further information).
Any clues?

**Comment by kloknibor** [comment]
This was an error that is fixed in a version released this week. Please make sure you are using the latest version and let me know if that works :-)

**Comment by jayatgithub** [comment]
Unfortunately not. I already had the latest version. I just removed it completely and reinstalled via HACS - still the same issue. Could this be a bug due to a wrong syntax in token path? I am using the following config in configuration.yaml:

miele:
    client_id: XXXXXXXXX
    client_secret: XXXXXXXX
    lang: de
    cache_path: /config/

**Comment by kloknibor** [comment]
Could you test if it works if you remove the cache_path? (which should be /config automatically anyway). thanks in advance!

**Comment by jayatgithub** [comment]
Yes! It worked by removing the whole line, as you suggested.
On the other hand, any path I tried (even /config - which seems to be default) turned into a 500. Maybe this information should find its way into the ReadMe.

Thanks!

**Comment by jaegerflo** [comment]
The add-on ran for me for a few months without any problems.
unfortunately not for a few days.
Source: custom_components/miele/miele_at_home.py:174

if I remove the path as described, the add-on starts but I get the 500 server error.

with path
Source: custom_components/miele/miele_at...

without path
500 servers error

Any solutions?
